In [10]:
import numpy as np
list_a=[1,3,5,7,9]
list_b=[2,4,6,8,10]
print(list_a+list_b)

array_a=np.array([1,3,5,7,9])
array_b=np.array([2,4,6,8,10])
print(array_a+array_b)

l=[[1,2,3],[4,5,6]]
array=np.array(l)
print(array)

[1, 3, 5, 7, 9, 2, 4, 6, 8, 10]
[ 3  7 11 15 19]
[[1 2 3]
 [4 5 6]]
